name: Semantic Pull Request

on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]

permissions: read-all

jobs:
  build:
    uses: The-FireHub-Project/.github/.github/workflows/SemanticPullRequest.yml@master
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}